"""Opaque, expiring, owner-bound files. No client-controlled native paths."""
from __future__ import annotations

import os
import re
import secrets
import stat
import time
from pathlib import Path

from .auth import Denied


class Artifacts:
    MAX_BYTES = 128 * 1024 * 1024

    def __init__(self, store, root: Path, *, clock=time.time):
        self.store, self.root, self.clock = store, root.absolute(), clock
        self.root.mkdir(parents=True, exist_ok=True, mode=0o700)
        if any(p.is_symlink() for p in (self.root, *self.root.parents)):
            raise ValueError("Artifact root must not contain symlinks")

    def publish(self, principal, content: bytes, extension: str):
        """Worker-only API: copies generated bytes, never adopts an arbitrary path."""
        if extension not in {"pdf", "pptx"} or len(content) > self.MAX_BYTES:
            raise ValueError("Invalid artifact")
        key = secrets.token_hex(24)
        filename = f"{key}.{extension}"
        fd = os.open(self.root / filename, os.O_WRONLY | os.O_CREAT | os.O_EXCL | os.O_NOFOLLOW, 0o600)
        with os.fdopen(fd, "wb") as stream:
            stream.write(content)
        try:
            self.store.write(principal.tenant, "artifact-" + key, {
                "owner": principal.owner, "extension": extension,
                "expires": int(self.clock()) + 3600, "sha256": digest_bytes(content), "size": len(content),
            }, expected=None)
        except Exception:
            self.discard(key, extension)
            raise
        return key

    def discard(self, key, extension):
        """Maintenance-only unlink, pinned to the artifact directory; no path input."""
        if not re.fullmatch(r"[0-9a-f]{48}", key) or extension not in {"pdf", "pptx"}:
            raise ValueError("Invalid artifact")
        directory = os.open(self.root, os.O_RDONLY | os.O_DIRECTORY | os.O_NOFOLLOW)
        try:
            filename = f"{key}.{extension}"
            try:
                info = os.stat(filename, dir_fd=directory, follow_symlinks=False)
            except FileNotFoundError:
                return
            if not stat.S_ISREG(info.st_mode):
                raise ValueError("Artifact must be a regular file")
            os.unlink(filename, dir_fd=directory)
        finally:
            os.close(directory)

    def download(self, principal, key):
        if not re.fullmatch(r"[0-9a-f]{48}", key):
            raise Denied(404, "artifact_not_found")
        row = self.store.read(principal.tenant, "artifact-" + key)
        if row is None or row.value["owner"] != principal.owner:
            raise Denied(404, "artifact_not_found")
        value = row.value
        if value["expires"] <= self.clock():
            raise Denied(410, "artifact_expired")
        extension = value["extension"]
        if extension not in {"pdf", "pptx"}:
            raise Denied(410, "artifact_unavailable")
        try:
            # Prevent root/file replacement by a symlink; directory descriptor pins
            # the same directory through openat, even if its name changes.
            directory = os.open(self.root, os.O_RDONLY | os.O_DIRECTORY | os.O_NOFOLLOW)
            try:
                fd = os.open(f"{key}.{extension}", os.O_RDONLY | os.O_NOFOLLOW, dir_fd=directory)
                with os.fdopen(fd, "rb") as stream:
                    content = stream.read(self.MAX_BYTES + 1)
            finally:
                os.close(directory)
        except OSError:
            raise Denied(410, "artifact_unavailable") from None
        if len(content) != value["size"] or digest_bytes(content) != value["sha256"]:
            raise Denied(410, "artifact_unavailable")
        return content, extension


def digest_bytes(value):
    import hashlib
    return hashlib.sha256(value).hexdigest()
